### ISSUE TITLE
Build breaks because of missing liboqs

### ISSUE THREAD

**Issue by jmccl** [facebookincubator/fizz#79] opened 2022-08-13 19:18 UTC
#include <oqs/kem.h> fails in the new file, OQSKeyExchange.h

https://github.com/facebookincubator/fizz/blob/7c31f0ab328d759c959e8307db0aee33e7e2388d/fizz/experimental/crypto/exchange/OQSKeyExchange.h

**Comment by mkyybx** [comment] 2022-08-13 21:48
Seems like it's caused by fizz tool including the experimental oqs implementation. Will try to use macros to disable it.

**Comment by mkyybx** [comment] 2022-08-15 18:47
That commit should've fixed that. I will close the issue now and should you still have trouble compiling, please feel free to reopen this issue.

**Closed by mkyybx** 2022-08-15 18:47 UTC
